import PDFDocument from "pdfkit";

const PAGE_MARGIN = 42;
const HEADER_HEIGHT = 68;
const FOOTER_HEIGHT = 28;
const BRAND = "#22d3ee";
const BRAND_SOFT = "#143043";
const SURFACE = "#0f172a";
const SURFACE_ALT = "#162033";
const SURFACE_CARD = "#111a2c";
const BORDER = "#293548";
const TEXT = "#e5eefb";
const MUTED = "#9fb0c5";
const SUCCESS = "#34d399";
const INPUT = "#7dd3fc";
const OUTPUT = "#c084fc";
const FONT_REGULAR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf";
const FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf";

export type PdfMetric = {
  label: string;
  value: string;
  tone?: "default" | "success" | "input" | "output";
};

export type SpendPdfRow = {
  name: string;
  subtitle?: string;
  tokens: string;
  cost: string;
  share?: string;
};

export type SpendPdfSection = {
  title: string;
  description?: string;
  rows: SpendPdfRow[];
};

export type SpendPdfSpec = {
  title: string;
  subtitle?: string;
  metrics: PdfMetric[];
  sections: SpendPdfSection[];
  footerNote?: string;
};

export type LedgerPdfEntry = {
  timestamp: string;
  provider: string;
  model: string;
  integration: string;
  project: string;
  team: string;
  source: string;
  agent: string;
  workflow: string;
  owner: string;
  inputTokens: string;
  outputTokens: string;
  totalTokens: string;
  cost: string;
};

export type LedgerPdfSpec = {
  title: string;
  subtitle?: string;
  metrics: PdfMetric[];
  entries: LedgerPdfEntry[];
  footerNote?: string;
};

type LedgerColumn = {
  key: keyof LedgerPdfEntry | "run" | "tokens";
  label: string;
  width: number;
  align?: "left" | "right";
};

function toneColor(tone?: PdfMetric["tone"]) {
  if (tone === "success") return SUCCESS;
  if (tone === "input") return INPUT;
  if (tone === "output") return OUTPUT;
  return BRAND;
}

function createDocument(layout: "portrait" | "landscape" = "portrait") {
  const doc = new PDFDocument({
    margin: PAGE_MARGIN,
    size: "A4",
    layout,
    bufferPages: true,
  });
  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));
  return { doc, chunks };
}

function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  const width = doc.page.width - PAGE_MARGIN * 2;
  doc.save();
  doc.roundedRect(PAGE_MARGIN, PAGE_MARGIN, width, HEADER_HEIGHT, 14).fill(SURFACE);
  doc.roundedRect(PAGE_MARGIN + 18, PAGE_MARGIN + 12, 120, 18, 9).fill(BRAND_SOFT);
  doc.fillColor(BRAND).font(FONT_BOLD).fontSize(9).text("TOKENOMETER", PAGE_MARGIN + 30, PAGE_MARGIN + 17, {
    width: 96,
    align: "center",
  });
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(22).text(title, PAGE_MARGIN + 18, PAGE_MARGIN + 28, {
    width: width - 36,
  });
  if (subtitle) {
    doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(10).text(subtitle, PAGE_MARGIN + 18, PAGE_MARGIN + 52, {
      width: width - 36,
    });
  }
  doc.restore();
  doc.y = PAGE_MARGIN + HEADER_HEIGHT + 18;
}

function drawFooter(doc: PDFKit.PDFDocument, pageNumber: number, footerNote?: string) {
  const y = doc.page.height - PAGE_MARGIN + 6;
  doc.strokeColor(BORDER).moveTo(PAGE_MARGIN, y - 10).lineTo(doc.page.width - PAGE_MARGIN, y - 10).stroke();
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(footerNote ?? "Generated by Tokenometer", PAGE_MARGIN, y, {
    width: doc.page.width - PAGE_MARGIN * 2 - 60,
  });
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(`Page ${pageNumber}`, doc.page.width - PAGE_MARGIN - 50, y, {
    width: 50,
    align: "right",
  });
}

function ensureSpace(
  doc: PDFKit.PDFDocument,
  nextHeight: number,
  title: string,
  subtitle?: string
) {
  const bottom = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT;
  if (doc.y + nextHeight <= bottom) return;
  doc.addPage();
  drawHeader(doc, title, subtitle);
}

function drawMetricCards(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string | undefined,
  metrics: PdfMetric[]
) {
  if (!metrics.length) return;
  const perRow = Math.min(metrics.length, 4);
  const gap = 12;
  const width = (doc.page.width - PAGE_MARGIN * 2 - gap * (perRow - 1)) / perRow;
  const height = 72;
  ensureSpace(doc, height + 10, title, subtitle);

  metrics.forEach((metric, index) => {
    const col = index % perRow;
    const row = Math.floor(index / perRow);
    const x = PAGE_MARGIN + col * (width + gap);
    const y = doc.y + row * (height + gap);
    const accent = toneColor(metric.tone);

    doc.save();
    doc.roundedRect(x, y, width, height, 12).fill(SURFACE_ALT);
    doc.roundedRect(x, y, 6, height, 12).fill(accent);
    doc.fillColor(MUTED).font(FONT_BOLD).fontSize(9).text(metric.label.toUpperCase(), x + 18, y + 14, {
      width: width - 32,
    });
    doc.fillColor(TEXT).font(FONT_BOLD).fontSize(18).text(metric.value, x + 18, y + 34, {
      width: width - 32,
    });
    doc.restore();
  });

  doc.y += Math.ceil(metrics.length / perRow) * (height + gap) + 8;
}

function drawSectionHeading(doc: PDFKit.PDFDocument, title: string, description?: string) {
  doc.strokeColor(BORDER).moveTo(PAGE_MARGIN, doc.y).lineTo(doc.page.width - PAGE_MARGIN, doc.y).stroke();
  doc.y += 10;
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(14).text(title, PAGE_MARGIN, doc.y);
  if (description) {
    doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(10).text(description, PAGE_MARGIN, doc.y + 2, {
      width: doc.page.width - PAGE_MARGIN * 2,
    });
  }
  doc.y += description ? 22 : 16;
}

function drawSpendTable(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string | undefined,
  section: SpendPdfSection
) {
  ensureSpace(doc, 120, title, subtitle);
  drawSectionHeading(doc, section.title, section.description);

  const tableWidth = doc.page.width - PAGE_MARGIN * 2;
  const columns = [tableWidth * 0.5, tableWidth * 0.18, tableWidth * 0.17, tableWidth * 0.15];
  const headerY = doc.y;

  doc.save();
  doc.roundedRect(PAGE_MARGIN, headerY, tableWidth, 26, 10).fill(SURFACE);
  const headers = ["Name", "Tokens", "Cost", "Share"];
  let x = PAGE_MARGIN;
  headers.forEach((header, index) => {
    doc.fillColor(MUTED).font(FONT_BOLD).fontSize(9).text(header, x + 10, headerY + 8, {
      width: columns[index] - 16,
      align: index === 0 ? "left" : "right",
    });
    x += columns[index];
  });
  doc.restore();
  doc.y += 32;

  section.rows.forEach((row, index) => {
    const nameHeight = doc.heightOfString(row.name, {
      width: columns[0] - 20,
      align: "left",
    });
    const subtitleHeight = row.subtitle
      ? doc.heightOfString(row.subtitle, {
          width: columns[0] - 20,
          align: "left",
        })
      : 0;
    const rowHeight = Math.max(38, nameHeight + subtitleHeight + (row.subtitle ? 18 : 12));

    ensureSpace(doc, rowHeight + 10, title, subtitle);
    if (index % 2 === 0) {
      doc.save();
      doc.roundedRect(PAGE_MARGIN, doc.y, tableWidth, rowHeight, 10).fill(SURFACE_CARD);
      doc.restore();
    }

    x = PAGE_MARGIN;
    doc.fillColor(TEXT).font(FONT_BOLD).fontSize(10).text(row.name, x + 10, doc.y + 8, {
      width: columns[0] - 20,
    });
    if (row.subtitle) {
      doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(row.subtitle, x + 10, doc.y + 22, {
        width: columns[0] - 20,
      });
    }
    x += columns[0];

    [
      { value: row.tokens, color: INPUT },
      { value: row.cost, color: SUCCESS },
      { value: row.share ?? "-", color: MUTED },
    ].forEach((cell, cellIndex) => {
      doc.fillColor(cell.color).font(cellIndex === 2 ? FONT_REGULAR : FONT_BOLD).fontSize(10).text(cell.value, x + 10, doc.y + 12, {
        width: columns[cellIndex + 1] - 20,
        align: "right",
      });
      x += columns[cellIndex + 1];
    });

    doc.y += rowHeight + 8;
  });

  doc.y += 4;
}

function drawNarrativeBlock(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string | undefined,
  label: string,
  body: string
) {
  const width = doc.page.width - PAGE_MARGIN * 2;
  const height = 64;
  ensureSpace(doc, height + 12, title, subtitle);
  doc.save();
  doc.roundedRect(PAGE_MARGIN, doc.y, width, height, 12).fill(SURFACE_ALT);
  doc.fillColor(MUTED).font(FONT_BOLD).fontSize(9).text(label.toUpperCase(), PAGE_MARGIN + 16, doc.y + 14, {
    width: width - 32,
  });
  doc.fillColor(TEXT).font(FONT_REGULAR).fontSize(11).text(body, PAGE_MARGIN + 16, doc.y + 30, {
    width: width - 32,
  });
  doc.restore();
  doc.y += height + 14;
}

function drawCompactLedgerMetrics(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string | undefined,
  metrics: PdfMetric[],
  footerNote?: string
) {
  if (!metrics.length) return;
  const width = doc.page.width - PAGE_MARGIN * 2;
  const rowHeight = 58;
  ensureSpace(doc, rowHeight + 10, title, subtitle);

  doc.save();
  doc.roundedRect(PAGE_MARGIN, doc.y, width, rowHeight, 12).fill(SURFACE_ALT);
  doc.restore();

  const usableWidth = width - 28;
  const perMetric = usableWidth / metrics.length;
  metrics.forEach((metric, index) => {
    const x = PAGE_MARGIN + 14 + perMetric * index;
    if (index > 0) {
      doc
        .strokeColor(BORDER)
        .moveTo(x - 8, doc.y + 10)
        .lineTo(x - 8, doc.y + rowHeight - 10)
        .stroke();
    }
    doc.fillColor(MUTED).font(FONT_BOLD).fontSize(8).text(metric.label.toUpperCase(), x, doc.y + 12, {
      width: perMetric - 14,
    });
    doc.fillColor(toneColor(metric.tone)).font(FONT_BOLD).fontSize(16).text(metric.value, x, doc.y + 26, {
      width: perMetric - 14,
    });
  });

  doc.y += rowHeight + 8;

  if (footerNote) {
    ensureSpace(doc, 26, title, subtitle);
    doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(footerNote, PAGE_MARGIN, doc.y, {
      width,
    });
    doc.y += 18;
  }
}

function drawLedgerCard(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string | undefined,
  entry: LedgerPdfEntry
) {
  const cardHeight = 126;
  const width = doc.page.width - PAGE_MARGIN * 2;
  ensureSpace(doc, cardHeight + 12, title, subtitle);

  doc.save();
  doc.roundedRect(PAGE_MARGIN, doc.y, width, cardHeight, 14).fill(SURFACE_CARD);
  doc.roundedRect(PAGE_MARGIN, doc.y, 6, cardHeight, 14).fill(BRAND);
  doc.restore();

  const topY = doc.y + 12;
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(12).text(`${entry.provider} / ${entry.model}`, PAGE_MARGIN + 18, topY, {
    width: width - 180,
  });
  doc.fillColor(SUCCESS).font(FONT_BOLD).fontSize(12).text(entry.cost, PAGE_MARGIN + width - 110, topY, {
    width: 92,
    align: "right",
  });

  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(entry.timestamp, PAGE_MARGIN + 18, topY + 18);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(`Total ${entry.totalTokens}`, PAGE_MARGIN + width - 110, topY + 18, {
    width: 92,
    align: "right",
  });

  const detailsX = PAGE_MARGIN + 18;
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(9).text("Integration", detailsX, topY + 40);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(entry.integration, detailsX + 58, topY + 40, {
    width: width * 0.42,
  });
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(9).text("Project", detailsX, topY + 56);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(entry.project, detailsX + 58, topY + 56, {
    width: width * 0.42,
  });
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(9).text("Team", detailsX, topY + 72);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(entry.team, detailsX + 58, topY + 72, {
    width: width * 0.42,
  });
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(9).text("Path", detailsX, topY + 88);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(entry.source, detailsX + 58, topY + 88, {
    width: width * 0.42,
  });

  const rightX = PAGE_MARGIN + width * 0.58;
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(9).text("Run", rightX, topY + 40);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(`${entry.agent} / ${entry.workflow}`, rightX + 48, topY + 40, {
    width: width * 0.32,
  });
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(9).text("Owner", rightX, topY + 56);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(entry.owner, rightX + 48, topY + 56, {
    width: width * 0.32,
  });
  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(9).text("Tokens", rightX, topY + 88);
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(`${entry.inputTokens} in / ${entry.outputTokens} out`, rightX + 48, topY + 88, {
    width: width * 0.32,
  });

  const metricsY = doc.y + cardHeight - 18;
  const metricWidth = (width - 70) / 3;
  [
    { label: "Input", value: entry.inputTokens, color: INPUT, x: PAGE_MARGIN + 18 },
    { label: "Output", value: entry.outputTokens, color: OUTPUT, x: PAGE_MARGIN + 18 + metricWidth },
    { label: "Total", value: entry.totalTokens, color: TEXT, x: PAGE_MARGIN + 18 + metricWidth * 2 },
  ].forEach((metric) => {
    doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(8).text(metric.label, metric.x, metricsY - 10);
    doc.fillColor(metric.color).font(FONT_BOLD).fontSize(10).text(metric.value, metric.x, metricsY + 2, {
      width: metricWidth - 10,
    });
  });

  doc.y += cardHeight + 10;
}

function drawLedgerSummaryRow(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string | undefined,
  entry: LedgerPdfEntry
) {
  const width = doc.page.width - PAGE_MARGIN * 2;
  const rowHeight = 40;
  ensureSpace(doc, rowHeight + 8, title, subtitle);

  doc.save();
  doc.roundedRect(PAGE_MARGIN, doc.y, width, rowHeight, 10).fill(SURFACE_ALT);
  doc.roundedRect(PAGE_MARGIN, doc.y, 5, rowHeight, 10).fill(BRAND);
  doc.restore();

  doc.fillColor(TEXT).font(FONT_BOLD).fontSize(10).text(`${entry.provider} / ${entry.model}`, PAGE_MARGIN + 16, doc.y + 10, {
    width: width * 0.48,
  });
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(entry.timestamp, PAGE_MARGIN + 16, doc.y + 23, {
    width: width * 0.3,
  });
  doc.fillColor(TEXT).font(FONT_REGULAR).fontSize(9).text(`${entry.integration} · ${entry.project}`, PAGE_MARGIN + width * 0.44, doc.y + 10, {
    width: width * 0.34,
  });
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(`${entry.agent} / ${entry.workflow}`, PAGE_MARGIN + width * 0.44, doc.y + 23, {
    width: width * 0.34,
  });
  doc.fillColor(SUCCESS).font(FONT_BOLD).fontSize(11).text(entry.cost, PAGE_MARGIN + width - 92, doc.y + 10, {
    width: 76,
    align: "right",
  });
  doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(9).text(`${entry.totalTokens} tokens`, PAGE_MARGIN + width - 118, doc.y + 23, {
    width: 102,
    align: "right",
  });

  doc.y += rowHeight + 10;
}

function drawLedgerTable(
  doc: PDFKit.PDFDocument,
  title: string,
  subtitle: string | undefined,
  entries: LedgerPdfEntry[]
) {
  drawSectionHeading(doc, "Filtered events", "Compact ledger rows for the current filter set.");

  if (!entries.length) {
    ensureSpace(doc, 44, title, subtitle);
    doc.fillColor(MUTED).font(FONT_REGULAR).fontSize(10).text(
      "No matching events for the current filters.",
      PAGE_MARGIN,
      doc.y + 8
    );
    doc.y += 24;
    return;
  }

  const width = doc.page.width - PAGE_MARGIN * 2;
  const columns: LedgerColumn[] = [
    { key: "timestamp", label: "Time", width: 0.12 },
    { key: "provider", label: "Provider", width: 0.12 },
    { key: "model", label: "Model", width: 0.14 },
    { key: "integration", label: "Integration", width: 0.14 },
    { key: "project", label: "Project", width: 0.11 },
    { key: "team", label: "Team", width: 0.11 },
    { key: "run", label: "Run", width: 0.13 },
    { key: "tokens", label: "Tokens", width: 0.08, align: "right" },
    { key: "cost", label: "Cost", width: 0.05, align: "right" },
  ];
  const resolvedColumns = columns.map((column) => ({
    ...column,
    width: width * column.width,
  }));

  const drawTableHeader = () => {
    ensureSpace(doc, 28, title, subtitle);
    doc.save();
    doc.roundedRect(PAGE_MARGIN, doc.y, width, 24, 8).fill(SURFACE);
    let x = PAGE_MARGIN;
    resolvedColumns.forEach((column) => {
      doc
        .fillColor(MUTED)
        .font(FONT_BOLD)
        .fontSize(8)
        .text(column.label.toUpperCase(), x + 8, doc.y + 8, {
          width: column.width - 16,
          align: column.align ?? "left",
        });
      x += column.width;
    });
    doc.restore();
    doc.y += 30;
  };

  drawLedgerSummaryRow(doc, title, subtitle, entries[0]);
  drawTableHeader();

  entries.forEach((entry, index) => {
    const values: Record<LedgerColumn["key"], string> = {
      timestamp: entry.timestamp,
      provider: entry.provider,
      model: entry.model,
      integration: entry.integration,
      project: entry.project,
      team: entry.team,
      source: entry.source,
      agent: entry.agent,
      workflow: entry.workflow,
      owner: entry.owner,
      inputTokens: entry.inputTokens,
      outputTokens: entry.outputTokens,
      totalTokens: entry.totalTokens,
      cost: entry.cost,
      run: `${entry.agent} / ${entry.workflow}`,
      tokens: `${entry.inputTokens} / ${entry.outputTokens} / ${entry.totalTokens}`,
    };

    const rowHeight = resolvedColumns.reduce((maxHeight, column) => {
      const height = doc.heightOfString(values[column.key], {
        width: column.width - 16,
        align: column.align ?? "left",
      });
      return Math.max(maxHeight, height);
    }, 0) + 12;

    if (doc.y + rowHeight > doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT) {
      doc.addPage();
      drawHeader(doc, title, subtitle);
      drawTableHeader();
    }

    if (index % 2 === 0) {
      doc.save();
      doc.roundedRect(PAGE_MARGIN, doc.y, width, rowHeight, 6).fill(SURFACE_CARD);
      doc.restore();
    }

    let x = PAGE_MARGIN;
    resolvedColumns.forEach((column) => {
      doc
        .fillColor(column.key === "cost" ? SUCCESS : TEXT)
        .font(column.key === "cost" ? FONT_BOLD : FONT_REGULAR)
        .fontSize(8.5)
        .text(values[column.key], x + 8, doc.y + 6, {
          width: column.width - 16,
          align: column.align ?? "left",
        });
      x += column.width;
    });

    doc.y += rowHeight + 4;
  });
}

export async function renderSpendPdfBuffer(spec: SpendPdfSpec): Promise<Buffer> {
  const { doc, chunks } = createDocument("portrait");
  drawHeader(doc, spec.title, spec.subtitle);
  drawMetricCards(doc, spec.title, spec.subtitle, spec.metrics);
  if (spec.footerNote) {
    drawNarrativeBlock(doc, spec.title, spec.subtitle, "Report note", spec.footerNote);
  }
  spec.sections.forEach((section) => drawSpendTable(doc, spec.title, spec.subtitle, section));

  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(index);
    drawFooter(doc, index + 1, spec.footerNote);
  }

  doc.end();

  return await new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}

export async function renderLedgerPdfBuffer(spec: LedgerPdfSpec): Promise<Buffer> {
  const { doc, chunks } = createDocument("landscape");
  drawHeader(doc, spec.title, spec.subtitle);
  drawCompactLedgerMetrics(doc, spec.title, spec.subtitle, spec.metrics, spec.footerNote);
  drawLedgerTable(doc, spec.title, spec.subtitle, spec.entries);

  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(index);
    drawFooter(doc, index + 1, spec.footerNote);
  }

  doc.end();

  return await new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}
