import PDFDocument from "pdfkit";

type PdfMetric = {
  label: string;
  value: string;
};

type PdfSection = {
  title: string;
  columns: string[];
  rows: string[][];
  columnWeights?: number[];
};

type PdfDocumentSpec = {
  title: string;
  subtitle?: string;
  metrics?: PdfMetric[];
  sections: PdfSection[];
  landscape?: boolean;
  footerNote?: string;
};

const PAGE_MARGIN = 40;
const HEADER_HEIGHT = 62;
const FOOTER_HEIGHT = 28;
const BRAND = "#22d3ee";
const SURFACE = "#0f172a";
const SURFACE_ALT = "#162033";
const BORDER = "#293548";
const TEXT = "#e5eefb";
const MUTED = "#9fb0c5";
const FONT_REGULAR = "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf";
const FONT_BOLD = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf";

function drawHeader(doc: PDFKit.PDFDocument, title: string, subtitle?: string) {
  const width = doc.page.width - PAGE_MARGIN * 2;
  doc.save();
  doc.roundedRect(PAGE_MARGIN, PAGE_MARGIN, width, HEADER_HEIGHT, 12).fill(SURFACE);
  doc
    .fillColor(BRAND)
    .fontSize(10)
    .font(FONT_BOLD)
    .text("TOKENOMETER", PAGE_MARGIN + 18, PAGE_MARGIN + 12);
  doc
    .fillColor(TEXT)
    .fontSize(20)
    .font(FONT_BOLD)
    .text(title, PAGE_MARGIN + 18, PAGE_MARGIN + 26, { width: width - 36 });
  if (subtitle) {
    doc
      .fillColor(MUTED)
      .fontSize(10)
      .font(FONT_REGULAR)
      .text(subtitle, PAGE_MARGIN + 18, PAGE_MARGIN + 47, {
        width: width - 36,
      });
  }
  doc.restore();
}

function drawFooter(doc: PDFKit.PDFDocument, pageNumber: number, footerNote?: string) {
  const footerY = doc.page.height - PAGE_MARGIN + 6;
  doc
    .strokeColor(BORDER)
    .moveTo(PAGE_MARGIN, footerY - 10)
    .lineTo(doc.page.width - PAGE_MARGIN, footerY - 10)
    .stroke();
  doc
    .fillColor(MUTED)
    .fontSize(9)
    .font(FONT_REGULAR)
    .text(
      footerNote ?? "Generated by Tokenometer",
      PAGE_MARGIN,
      footerY,
      { width: doc.page.width - PAGE_MARGIN * 2 - 60 }
    );
  doc
    .fillColor(MUTED)
    .fontSize(9)
    .font(FONT_REGULAR)
    .text(`Page ${pageNumber}`, doc.page.width - PAGE_MARGIN - 50, footerY, {
      width: 50,
      align: "right",
    });
}

function ensureSpace(
  doc: PDFKit.PDFDocument,
  nextBlockHeight: number,
  headerTitle: string,
  headerSubtitle?: string
) {
  const bottomLimit = doc.page.height - PAGE_MARGIN - FOOTER_HEIGHT;
  if (doc.y + nextBlockHeight <= bottomLimit) return;
  doc.addPage();
  drawHeader(doc, headerTitle, headerSubtitle);
  doc.y = PAGE_MARGIN + HEADER_HEIGHT + 16;
}

function computeColumnWidths(totalWidth: number, columns: number, weights?: number[]) {
  if (!weights || weights.length !== columns) {
    return Array.from({ length: columns }, () => totalWidth / columns);
  }
  const totalWeight = weights.reduce((sum, weight) => sum + weight, 0) || columns;
  return weights.map((weight) => (totalWidth * weight) / totalWeight);
}

function drawMetrics(
  doc: PDFKit.PDFDocument,
  metrics: PdfMetric[],
  headerTitle: string,
  headerSubtitle?: string
) {
  if (!metrics.length) return;
  const perRow = Math.min(metrics.length, 4);
  const gap = 12;
  const width =
    (doc.page.width - PAGE_MARGIN * 2 - gap * (perRow - 1)) / perRow;
  const height = 64;
  ensureSpace(doc, height + 12, headerTitle, headerSubtitle);
  metrics.forEach((metric, index) => {
    const col = index % perRow;
    const row = Math.floor(index / perRow);
    const x = PAGE_MARGIN + col * (width + gap);
    const y = doc.y + row * (height + gap);
    doc.save();
    doc.roundedRect(x, y, width, height, 10).fill(SURFACE_ALT);
    doc
      .fillColor(MUTED)
      .fontSize(9)
      .font(FONT_BOLD)
      .text(metric.label.toUpperCase(), x + 14, y + 12, { width: width - 28 });
    doc
      .fillColor(TEXT)
      .fontSize(18)
      .font(FONT_BOLD)
      .text(metric.value, x + 14, y + 28, { width: width - 28 });
    doc.restore();
  });
  doc.y += Math.ceil(metrics.length / perRow) * (height + gap);
}

function drawTable(
  doc: PDFKit.PDFDocument,
  section: PdfSection,
  headerTitle: string,
  headerSubtitle?: string
) {
  const tableWidth = doc.page.width - PAGE_MARGIN * 2;
  const colWidths = computeColumnWidths(tableWidth, section.columns.length, section.columnWeights);
  const headerHeight = 24;
  const rowHeight = 20;
  ensureSpace(
    doc,
    headerHeight + rowHeight * Math.min(section.rows.length + 1, 12) + 40,
    headerTitle,
    headerSubtitle
  );

  doc
    .fillColor(TEXT)
    .fontSize(13)
    .font(FONT_BOLD)
    .text(section.title, PAGE_MARGIN, doc.y, { width: tableWidth });
  doc.y += 18;

  let x = PAGE_MARGIN;
  doc.save();
  doc.roundedRect(PAGE_MARGIN, doc.y, tableWidth, headerHeight, 8).fill(SURFACE);
  section.columns.forEach((column, index) => {
    doc
      .fillColor(MUTED)
      .fontSize(9)
      .font(FONT_BOLD)
      .text(column, x + 8, doc.y + 7, {
        width: colWidths[index] - 16,
        ellipsis: true,
      });
    x += colWidths[index];
  });
  doc.restore();
  doc.y += headerHeight;

  section.rows.forEach((row, rowIndex) => {
    ensureSpace(doc, rowHeight + 8, headerTitle, headerSubtitle);
    x = PAGE_MARGIN;
    if (rowIndex % 2 === 0) {
      doc.save();
      doc.roundedRect(PAGE_MARGIN, doc.y, tableWidth, rowHeight, 6).fill("#111a2c");
      doc.restore();
    }
    row.forEach((cell, index) => {
      doc
        .fillColor(TEXT)
        .fontSize(9)
        .font(FONT_REGULAR)
        .text(cell, x + 8, doc.y + 6, {
          width: colWidths[index] - 16,
          ellipsis: true,
        });
      x += colWidths[index];
    });
    doc.y += rowHeight;
  });

  doc.y += 14;
}

export async function renderPdfBuffer(spec: PdfDocumentSpec): Promise<Buffer> {
  const doc = new PDFDocument({
    margin: PAGE_MARGIN,
    size: "A4",
    layout: spec.landscape ? "landscape" : "portrait",
    bufferPages: true,
  });

  const chunks: Buffer[] = [];
  doc.on("data", (chunk) => chunks.push(Buffer.from(chunk)));

  drawHeader(doc, spec.title, spec.subtitle);
  doc.y = PAGE_MARGIN + HEADER_HEIGHT + 18;

  if (spec.metrics?.length) {
    drawMetrics(doc, spec.metrics, spec.title, spec.subtitle);
    doc.y += 6;
  }

  spec.sections.forEach((section) => drawTable(doc, section, spec.title, spec.subtitle));

  const range = doc.bufferedPageRange();
  for (let index = 0; index < range.count; index += 1) {
    doc.switchToPage(index);
    drawFooter(doc, index + 1, spec.footerNote);
  }

  doc.end();

  return await new Promise<Buffer>((resolve, reject) => {
    doc.on("end", () => resolve(Buffer.concat(chunks)));
    doc.on("error", reject);
  });
}
